### ISSUE TITLE
Failed to load the xkcd-comics package

### ISSUE THREAD

**Issue by RodolpheAubry** [peduxe/xkcd-comics#2]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [xkcd-comics](https://github.com/peduxe/xkcd-comics) package, v0.3.0

### Stack Trace

Failed to load the xkcd-comics package

```
At Cannot find module 'lodash/function/debounce'

Error: Cannot find module 'lodash/function/debounce'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/rod/.atom/packages/xkcd-comics/lib/view.js:4:37)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/rod/.atom/packages/xkcd-comics/lib/xkcd.js:3:37)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/rod/.atom/packages/xkcd-comics/lib/main.js:2:41)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:722:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.20.0
highlight-selected, v0.11.2
minimap, v4.19.0
open-recent, v5.0.0
pigments, v0.23.1
seti-ui, v0.8.1
xkcd-comics, v0.3.0

# Dev
No dev packages
```

**Comment by meehanman** [comment]
+1

**Comment by peduxe** [comment]
Fixed in https://github.com/peduxe/xkcd-comics/commit/e3d612959d561bb8090da3f1c5ff3bb60be1544e

**Comment by peduxe** [comment]
I will do a major overhaul on this package next week, stay tuned :)

**Comment by Bob-Thomas** [comment]
Can't wait :3

**Comment by fundor333** [comment]
When are yu going to update?

**Comment by Kosai106** [comment]
I can report that this still haven't been fixed.

**Comment by RothNRK** [comment]
In my opinion this package settled the "What text editor should I really use?" Clearly the answer is Atom, why? Because you can get xkcd delivered to you. My heart sank when I installed the package and got the reported errors.

**Comment by Joeasaurus** [comment]
👍

**Comment by Jarvvski** [comment]
This is still broken as of current build

**Comment by maximus136** [comment]
Still broken!

**Comment by fundor333** [comment]
Still broken

**Comment by daniel-kipkemei** [comment]
not working

**Comment by shubhamjain0594** [comment]
Still broken

**Comment by numitori** [comment]
Sadly broken

**Comment by aleksey-korotkevich** [comment]
@peduxe 
Hi there, I have fix this issue (and, probably, [the second one](https://github.com/peduxe/xkcd-comics/issues/3) opened) and created [Pull Request](https://github.com/peduxe/xkcd-comics/pull/4)

It will be great if you can review this PR and merge it ASAP, so that no one will face this error again in future.
And you will be able to close to issues in your repo :)

**Comment by DavidTaveira** [comment]
sadly still not working...

**Comment by Joeasaurus** [comment]
Thanks for your work @aleksey-korotkevich, hopefully it will be merged soon!

**Comment by jradesenv** [comment]
still not working

**Comment by peduxe** [comment]
merged now tho

I haven't had much time to spend on this but anyone is welcome to clone and release a "spinoff" of this package

**Comment by perchslayer** [comment]
How do I get rid of it so that I don't get the error message anymore. That is, how do you "surgically" remove it and all of the dependencies?

**Comment by perchslayer** [comment]
I am ready to cut my losses on this package, but I don't want to have to re-install atom because of it. Is that possible?

**Comment by RothNRK** [comment]
@perchslayer 
From terminal 
`rm -r .atom/packages/xkcd-comics/`

**Comment by ipentest** [comment]
Its still the same issue... Me too using rm -r .atom/packages/xkcd-comics/

**Comment by Jarvvski** [comment]
@ipentest please paste the output of `ls ~/.atom/packages/ | cat`

**Comment by RothNRK** [comment]
So this will get it up:

1) Install xkcd-comics using Atom's [apm](https://github.com/atom/apm)
`apm install https://github.com/peduxe/xkcd-comics.git`
2) Install opn [opn](https://github.com/sindresorhus/opn)
`npm install --save opn`
